---
- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true
- name: Install Nginx
  ansible.builtin.apt:
    name:
      - nginx
      - php-mbstring
      - php-xml
      - php-bcmath
      - mysql-server
      - p7zip
      - unzip
      - php-fpm 
      - php-mysql
    state: present
  become: true
- name: Install Nginx configs
  block:
    - name: Install nginx.conf
      ansible.builtin.template:
        src: templates/nginx.conf
        dest: /etc/nginx/nginx.conf
        force: true
    - name: Install site config
      ansible.builtin.template:
        src: templates/nginx_laravel.conf
        dest: /etc/nginx/conf.d/{{ laravel.app_name }}.conf
        force: true
  become: true
- name: Install composer
  block:
    - name: Download composer setup
      ansible.builtin.get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        checksum: sha384:55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae
    - name: Run the installer
      ansible.builtin.shell: php composer-setup.php
      args:
        chdir: /tmp
        creates: /tmp/composer.phar
    - name: Copy composer executable
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/composer.phar
        dest: /usr/local/bin/composer
        mode: preserve
  become: true
