---
- name: Prepare the docker installation
  block:
    - name: Download repo key
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add docker repo to the apt sources
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Clean possible previous docker version
  ansible.builtin.apt:
    name: 
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
- name: Add docker user account
  ansible.builtin.user:
    name: docker
    password: "!"
    group: docker
- name: Enable Docker service
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started
- name: Set folder owner
  ansible.builtin.shell:
    cmd: chown -R docker:docker /opt

