---
- name: Create docker network
  community.docker.docker_network:
    name: "{{ service_network }}"
- name: Deploy PHP
  community.docker.docker_container:
    name: "{{ php.name }}"
    image: "{{ php.image }}"
    networks:
      - name: "{{ php.network }}"
    volumes: 
      - "{{ php.volume }}:/app"
    restart_policy: always
- name: Deploy nginx
  community.docker.docker_container:
    name: "{{ nginx.name }}"
    image: "{{ nginx.image }}"
    networks:
      - name: "{{ nginx.network }}"
    volumes:
      - "{{ nginx.volume }}:/var/www/data"
    restart_policy: always
    published_ports: 
      - "{{ nginx.ports }}"
- name: Deploy MySQL
  community.docker.docker_container:
    name: "{{ mysql.name }}"
    image: "{{ mysql.image }}"
    networks:
      - name: "{{ mysql.network }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql.root_pass }}"
      MYSQL_DATABASE: "{{ mysql.database_name }}"
    restart_policy: always
