---
- name: Run preparation tasks
  ansible.builtin.include: 01_prepare.yml
- name: Add user
  ansible.builtin.include: 02_user.yml
- name: Deploy services
  ansible.builtin.include: 03_create_app.yml
- name: Start services
  ansible.builtin.include: 04_run-services.yml
- name: Iptable rules
  ansible.builtin.include: 05_iptables.yml
