---
# handlers file for bq-test

nginx:
  workers: auto
  servername: bucklequick.ru
laravel:
  host: 127.0.0.1
  port: 8000
  app_name: test-app
  app_env: development
  app_key: APPLICATION_UNIQUE_KEY_DONT_COPY
  app_debug: true
  app_url: http://bucklequick.ru
  log_channel: stack
  db:
    connection: mysql
    host: 127.0.0.1
    port: 3306
    database: testapp
    username: testapp
    password: testapp


user_name: ubuntu

