---
  - name: System prepare
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Add local user
        ansible.builtin.user:
          name: alex
          shell: /bin/bash
          groups: sudo,admin
          append: yes
      - name: Add user public key
        ansible.posix.authorized_key:
          user: alex
          state: present
          key: "{{ lookup('file', './temp_key.pub') }}"

